# -*- coding: utf-8 -*-
"""Procesamiento de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJrru2XIMFeGFG2-81nJbOvURqYvMdyv
"""



import numpy as np
import pandas as pd
sellers = pd.read_csv('olist_sellers_dataset.csv')
sellers[:10]

customers = pd.read_csv('olist_customers_dataset.csv')
customers[:10]

geolocations = pd.read_csv("olist_geolocation_dataset.csv")
geolocations[:10]

items = pd.read_csv("olist_order_items_dataset.csv")
items[:10]

payments = pd.read_csv("olist_order_payments_dataset.csv")
payments[:10]

products = pd.read_csv("olist_products_dataset.csv")
products[:10]

reviews = pd.read_csv("olist_order_reviews_dataset.csv")
reviews[:10]

orders = pd.read_csv("olist_orders_dataset.csv")
orders[:10]

Final_data = pd.merge(orders, customers, on='customer_id', how='inner')
# To merge more dataframes, you would chain .merge() calls or perform them sequentially.
# Example for the next step, merging with reviews:
Final_data = pd.merge(Final_data, reviews, on='order_id', how='inner')
Final_data = pd.merge(Final_data, payments, on='order_id', how='inner')
Final_data = pd.merge(Final_data, items, on='order_id', how='inner')
Final_data = pd.merge(Final_data, products, on='product_id', how='inner')
Final_data = pd.merge(Final_data, sellers, on='seller_id', how='inner')
Final_data

Final_data.columns

len(Final_data["customer_id"].unique())

customer_purchase_data = Final_data[['customer_unique_id', 'order_purchase_timestamp']].copy()
customer_purchase_data['order_purchase_timestamp'] = pd.to_datetime(customer_purchase_data['order_purchase_timestamp'])
print(customer_purchase_data.head())
print(customer_purchase_data.info())

snapshot_date = customer_purchase_data['order_purchase_timestamp'].max() + pd.DateOffset(days=1)
print(f"Snapshot Date: {snapshot_date}")

last_purchase_date = customer_purchase_data.groupby('customer_unique_id')['order_purchase_timestamp'].max().reset_index()
last_purchase_date.columns = ['customer_unique_id', 'last_purchase_date']
print(last_purchase_date.head())

rfm_data = pd.DataFrame(last_purchase_date['customer_unique_id'])
rfm_data['Recency'] = (snapshot_date - last_purchase_date['last_purchase_date']).dt.days
print(rfm_data.head())

churn_threshold = 90  # Example: 90 days
rfm_data['churned'] = rfm_data['Recency'].apply(lambda x: 1 if x > churn_threshold else 0)
print(rfm_data.head())

print(rfm_data.head())
print(rfm_data.info())

frequency_df = Final_data.groupby('customer_unique_id')['order_id'].nunique().reset_index()
frequency_df.columns = ['customer_unique_id', 'Frequency']
print(frequency_df.head())

monetary_df = Final_data.groupby('customer_unique_id')['payment_value'].sum().reset_index()
monetary_df.columns = ['customer_unique_id', 'Monetary']
print(monetary_df.head())

rfm_data = pd.merge(rfm_data, frequency_df, on='customer_unique_id', how='left')
print(rfm_data.head())

rfm_data = pd.merge(rfm_data, monetary_df, on='customer_unique_id', how='left')
print(rfm_data.head())

print(rfm_data.head())
print(rfm_data.info())

rfm_data.to_csv('rfm_data.csv', index=False)

Final_data['order_purchase_timestamp'] = pd.to_datetime(Final_data['order_purchase_timestamp'])
Final_data['shipping_limit_date'] = pd.to_datetime(Final_data['shipping_limit_date'])

# Calculate shipping time for each order in days
Final_data['shipping_time'] = (Final_data['shipping_limit_date'] - Final_data['order_purchase_timestamp']).dt.total_seconds() / (24 * 3600)

# Calculate average shipping time per unique customer
avg_shipping_time_df = Final_data.groupby('customer_unique_id')['shipping_time'].mean().reset_index()
avg_shipping_time_df.columns = ['customer_unique_id', 'avg_shipping_time']

# Merge the average shipping time into rfm_data
rfm_data = pd.merge(rfm_data, avg_shipping_time_df, on='customer_unique_id', how='left')

print(rfm_data.head())
avg_review_score_df = Final_data.groupby('customer_unique_id')['review_score'].mean().reset_index()
avg_review_score_df.columns = ['customer_unique_id', 'avg_review_score']

# Merge the average review score into rfm_data
rfm_data = pd.merge(rfm_data, avg_review_score_df, on='customer_unique_id', how='left')

print(rfm_data.head())
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
model = LogisticRegression()
X = rfm_data.drop("churned", axis=1)
y = rfm_data["churned"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
numerical_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
X_train_processed = X_train[numerical_cols]
X_test_processed = X_test[numerical_cols]

# Fill any remaining NaN values in numerical columns, e.g., with the mean
# This is a good practice as models often don't handle NaNs directly
X_train_processed = X_train_processed.fillna(X_train_processed.mean())
X_test_processed = X_test_processed.fillna(X_test_processed.mean())
import mlflow
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import mlflow.sklearn
mlflow.set_experiment("Churn_prediction_Logreg")
with mlflow.start_run(run_name="Logistic Regression Model"):
    tol = 1e-5
    penalty = "l1"
    C = 1.0
    fit_intercept = True            # Start a new MLflow run.
    # Instantiate a LogisticRegression model with default parameters
    initial_model = LogisticRegression(random_state=42,tol=tol,penalty=penalty,fit_intercept=fit_intercept) # Added random_state for reproducibility

    # Fit the model to the training data
    initial_model.fit(X_train_processed, y_train)

    # Log the model
    mlflow.sklearn.log_model(initial_model, "initial_logistic_regression_model")

    # Make predictions on the test set
    y_pred_initial = initial_model.predict(X_test_processed)

    # Calculate and log accuracy
    accuracy_initial = accuracy_score(y_test, y_pred_initial)
    mlflow.log_metric("accuracy", accuracy_initial)

    # Generate and log classification report as an artifact
    report_initial = classification_report(y_test, y_pred_initial, output_dict=True)
    mlflow.log_dict(report_initial, "initial_classification_report.json")

    print(f"Initial Logistic Regression Model logged with accuracy: {accuracy_initial}")
    print("Check MLflow UI for more details.")
